package com.spring.auth.model;

import javax.persistence.*;

import lombok.AllArgsConstructor; // Lombok annotation for generating a constructor with all fields
import lombok.Data; // Lombok annotation for generating getters, setters, equals(), hashCode(), and toString()
import lombok.NoArgsConstructor; // Lombok annotation for generating a no-argument constructor

/**
 * This class represents a user in the application.
 * It corresponds to a table in the database.
 */
@Entity
@Table(name = "users")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserName {

    /**
     * The unique identifier for the user.
     * This field is marked as the primary key and auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id")
    private Long id;

    /**
     * The username of the user.
     */
    @Column(name="username")
    private String username;

    /**
     * The password of the user.
     * Important: Never store plain text passwords in the database!
     * You should hash the password before saving it using a strong hashing algorithm like BCrypt.
     */
    @Column(name="password")
    private String password;
}
